version: '2'

services:
  nginx:
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    environment:
      - METEOR_SERVER
      - DOCKER_SERVER
      - DOLLAR=$$
    volumes:
      - ./nginx/default.conf:/tmp/default.conf:ro
      - ./ssl:/usr/share/nginx/ssl
      - ./ssl/itcenter_onsip.crt:/etc/nginx/ssl/cert.pem:ro
      - ./ssl/itcenter_onsip.key:/etc/nginx/ssl/key.pem:ro
    command: /bin/bash -c "envsubst < /tmp/default.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      itcenter_sip_net:
        ipv4_address: 172.21.0.8
networks:
  itcenter_sip_net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.21.0.0/24
